### ISSUE TITLE
Professor Dean Feedback [Umbrella Issue]

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/usaco-guide#141]
- [x] Integrating w/ USACO homepage (see #139) @thecodingwizard 
- [x] User accounts (discussion ongoing) @thecodingwizard 
- [x] Top page wording
- [x] William's youtube video monetization (see #145) @thecodingwizard 
- [x] Merging resource lists (see #142) @bqi343 (being discussed on slack)
- [x] Olympiad terminology
- [x] Remove "an interesting read" article
- [x] Shorten templates (rules are prohibiting pre-written code) (see #144) @caoash 
- [x] "Factors to Consider" remove "USACO problemsetters don't always test"
- [x] remove USACO camp page
- [x] C++ Tips & Tricks: `sort(1+all(v))` is sketchy. NTT is not needed @nchn27 
- [x] Figure out how to tell people that "plat topics can appear in gold" @thecodingwizard (added warnings to all of the section pages)
- [x] Advanced topics are beyond scope of USACO contests... (I personally think this is fine though?) @bqi343 @thecodingwizard 
- [x] bronze intro to DS (memory, array initialization -- check email!) @darren-yao 
- [x] bronze rectangle geometry too specific @frodakcin 
- [x] bronze recursive complete search should be silver (see #146) @caoash 
- [x] bronze sorting designate as "bonus" @nchn27 
- [x] bronze data structure: only array/vector required [Currently only array/vector, pair/tuple and that should be okay] @darren-yao 
- [x] bronze greedy disclaimer @nchn27 
- [x] bronze graphs photos + misc @caoash (note: linked resources already have photos)
- [x] silver functional graphs too specific @frodakcin 
- [x] silver sort and scan / sweepline module missing ?? big one, who wants to do it
- [x] gold max suffix query w/ insertions only ==> too specific @bqi343 

Open a new issue if you want to discuss one of the following in-depth :)

(btw, I just randomized assignments. Feel free to work on whatever you want -- just edit this post)
