### ISSUE TITLE
Searching Problems

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/usaco-guide#86]
## Incomplete Features

Note that this list is not necessarily ordered by importance.

- [ ] Dark Mode #4152 
- [ ] better mobile support?
- [ ] search by + display division (Bronze - Plat) of the module that contains the problem
- [ ] option to select a random (unsolved) problem from a division
- [ ] save searches + create problemsets
- [ ] add link to user solutions? ex. https://usaco.guide/problems/ys-montmort/user-solutions
- [ ] optimize algolia operations usage? https://github.com/cpinitiative/usaco-guide/issues/86#issuecomment-1873341366
- [ ] properly handle "search by status"? ie. separate search by status and search by name into two separate searching systems if we exceed 1000 problems / Algolia's limit on refinements: https://github.com/cpinitiative/usaco-guide/pull/4157#discussion_r1439093684

---

from https://github.com/cpinitiative/usaco-guide/issues/86#issuecomment-788536196 (note that this list may be a bit outdated):

okay so here was what I am thinking (am open to changes):
- tags should look a lot nicer. Perhaps we can do something like "category" on the e-commerce demo, or add a searchable list of tags, idk. in general tags UI needs to be improved
- there should be an option to increase the number of hits per page, as well as pagination
- difficulty / module division should be displayed
- should have option to filter by difficulty / module(s)
- should have option to show starred only
- show whether user solved the problem yet

we should also allow users to use problems page to create randomized problemsets to do. this would entail:
- all of the filtering functionality above
- have an option to randomize the problems & hide difficulty / tags / modules
- (far future) save searches / problemsets

---

## Completed Features

- [x] search by + display tags
- [x] search by + display problem name
- [x] search by + display starred
- [x] search by + display source
- [x] search by + display module
- [x] show whether user solved the problem yet
- [x] search by + display difficulty (relative to module) #3320
- [x] option to increase the number of hits per page, as well as pagination #3394
- [x] option to hide difficulty / tags / modules #3394
- [x] edit problem status from search page

**Comment by bqi343** [comment]
Request for searching by source (ex. USACO Plat) + difficulty.

**Comment by thecodingwizard** [comment]
Difficulty is questionable... (Wormhole sort is both easy and insane XD)

**Comment by bqi343** [comment]
> Difficulty is questionable... (Wormhole sort is both easy and insane XD)

Taking min difficulty could be okay. Also,

> hide solution links on the problems page if the user has tags + solutions off

Hide tags as well?

**Comment by bqi343** [comment]
> Request for searching by source (ex. USACO Plat) + difficulty.

O also contest I guess (ex. Open 19)

**Comment by MrinallU** [comment]
So like in the problems page what if we had like three filter options, one to search by name, one by tag and one by difficulty, although I think difficulty is pretty relative based  on the person.

**Comment by thecodingwizard** [comment]
You should be able to use all three filters at once (see https://react-instantsearch.netlify.app/examples/e-commerce/ or something like that)

**Comment by MrinallU** [comment]
I see...

**Comment by MrinallU** [comment]
So does each problem have this data (more specifically does each problem have its own tags and difficulty measure?)

**Comment by bqi343** [comment]
- todo: fix updating problem tags

**Comment by MrinallU** [comment]
@thecodingwizard Can I get assigned to this?

**Comment by thecodingwizard** [comment]
okay so here was what I am thinking (am open to changes):
- tags should look a lot nicer. Perhaps we can do something like "category" on the e-commerce demo, or add a searchable list of tags, idk. in general tags UI needs to be improved
- there should be an option to increase the number of hits per page, as well as pagination
- difficulty / module division should be displayed
- should have option to filter by difficulty / module(s)
- should have option to show starred only
- show whether user solved the problem yet

we should also allow users to use problems page to create randomized problemsets to do. this would entail:
- all of the filtering functionality above
- have an option to randomize the problems & hide difficulty / tags / modules
- (far future) save searches / problemsets

**Comment by cirex-web** [comment]
Is this issue closed already? It seems like problem searching [is already available](https://usaco.guide/problems/).

**Comment by thecodingwizard** [comment]
no. it's missing features described above :(

**Comment by thecodingwizard** [comment]
Somehow this happened:

![image](https://github.com/cpinitiative/usaco-guide/assets/7865976/d757b3e2-580e-430a-977a-95e157bdeac9)

I don't think this has ever happened before. We may want to consider optimizing searches / operations usage if this continues to be a problem.

(cc @devo1ution)

**Comment by devo1ution** [comment]
oh shoot wait im so sorry...I think each individual refine call got counted as an operation so filtering to not attempted would immediately take ~1000 operations 😭 I've changed it to use setIndexUiState to combine all these operations into 1, so we shouldn't run into this issue in the future.

Sorry!

**Comment by thecodingwizard** [comment]
Oh that makes sense, thanks for letting me know! Don't worry about it -- mistakes happen and this is totally fine as long as it's not likely to be a recurring issue.

> Also if we have to pay for a temporary upgrade (if thats a thing) I'm completely willing to 😓

Thanks very kind of you but you really don't have to (CPI will generally pay for all development costs, including mistakes)! I was trying to see if it's possible to temporarily upgrade the plan, but we're on a legacy open-source plan so I don't even see the option to pay for more usage at the moment :p

**Comment by ghost** [comment]
Please include sorting option. by difficulty and section.
#5681
